name: Add Discord deb packages

on:
  schedule:
    - cron: "17 4 * * *"
  workflow_dispatch:

jobs:
  add-discord-package:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }} # Uses your PAT instead of GITHUB_TOKEN to trigger subsequent workflows

      - name: Download Discord package
        run: |
          wget --content-disposition "https://discord.com/api/download?platform=linux"
          mv discord-*.deb packages
          git add packages/

          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected!"

            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"

            git commit -m "chore: add Discord deb packages"
            git push origin main
          else
            echo "No changes, working copy is clean."
            exit 0
          fi
