name: Generate the site (APT repository)

on:
  push:
    branches:
      - main
    paths:
      - packages/**
  workflow_dispatch:

jobs:
  gen-site:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Import GPG Key
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.gnupg
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          chmod 700 ~/.gnupg
          # Restart the agent to apply changes
          gpgconf --kill gpg-agent

          # Import using the passphrase secret
          echo "${GPG_PRIVATE_KEY}" | gpg --batch --no-tty --passphrase "${GPG_PASSPHRASE}" --import

      - name: Generate the site (APT repository)
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          sudo apt update
          sudo apt install -y aptly

          aptly repo create discord
          aptly repo add discord packages/*.deb
          aptly publish repo -distribution=stable -passphrase="${GPG_PASSPHRASE}" discord
          # It publishes the repo in ~/.aptly/public/

          rsync -avP --delete ~/.aptly/public/ site/

          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git add site/
          # Only commit and push if there are actual changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: add site" && git push origin main)
